# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
templates:
    params:
        author-email: stphndemos@gmail.com
        author-name: Stephen Demos
        category: Web
        license: MIT
        copyright: 2016 Stephen Demos
        github-username: sdemos
