#!/bin/bash

# run the urxvt daemon
urxvtd -q -o -f

# set some xserver parameters
xset -dpms
xset s 0
xset r rate 300 60

# make the scrolling on my thinkpad work
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5

# turn off the trackpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0

# set up the feh background
source /home/demos/.fehbg

# make my cool keybindings work
xbindkeys
